---
- hosts: fedoras
  remote_user: root

  vars_prompt:
  - name: "usuario"
    prompt: "teclee nuevo usuario"
    private: no

  tasks:
  - name: crear nuevo usuario
    user: name={{ usuario }}
          password=$6$2nSjiQhD41PczpGI$rm4.LoIbMKYiEnFekAYifMFVRtr.XEkZj5wHDNnnxSw54gPZycAbL9yZ1N8QwWIZFOc/5YV4p2z9iaBTSBHci/
          append=no
          shell="/bin/bash"
    when: usuario is defined
...
